services:

  mysql:
    image: mysql:latest
    ports:
        - 3306:3306
    volumes:
        - /tmp/data/:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - TZ=America/Argentina/Mendoza
    networks:
      - flask-app

  app:
    build:
      context: .
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    environment:
      - HOST=mysql
    networks:
      - flask-app

networks:
  flask-app:
      