services:

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      - flask-app

  app:
    build:
      context: .
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      - HOST=postgres
    networks:
      - flask-app

networks:
  flask-app:
      